# Generated by Django 4.1.5 on 2023-01-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my', models.CharField(max_length=1000)),
                ('res', models.CharField(max_length=1000)),
            ],
        ),
    ]
