# Generated by Django 4.1.5 on 2023-01-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Saj',
            new_name='Sajith',
        ),
    ]
