# Generated by Django 4.1.5 on 2023-01-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_saj_sajith'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sajith',
            new_name='chat',
        ),
    ]
